### ISSUE TITLE
Remove Linux submodule?

### ISSUE THREAD

**Issue by jeremyckahn** [psema4/pine#4]
I set up a submodule for the Raspberry Pi version of Linux [here](https://github.com/jeremyckahn/pine/tree/master/dep).  It looks like we don't really need it anymore.  @psema4, do you think it serves any value at this point?

**Comment by psema4** [comment]
Using the Raspbian image as we're currently doing is probably the best bet for the foreseeable future

The Cross-LFS (ARM) document might be better suited to a custom Linux distro since it walks through everything from start to finish so I suspect it's safe to remove; certainly it would be easy enough to add again should we need it in the future.

**Comment by jeremyckahn** [comment]
Makes sense to me.  Removed Linux submodule in 34bdde9f4605b0473fc9759a5b1eb54addf69e19.
